export const data = [
  {
    gameNo: "GSLG01",
    home: "SAVIO",
    away: "BANTU SPORTS",
    conference: "WESTERN",
    day: "SAT",
    date: "4TH MARCH",
    time: "10.00AM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG02",
    home: "JERICHO VIPERS",
    away: "JERICHO NETS",
    conference: "WESTERN",
    day: "SAT",
    date: "4TH MARCH",
    time: "11.50AM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG03",
    home: "FEBA ACADEMY",
    away: "JUNUBIN NATION",
    conference: "WESTERN",
    day: "SAT",
    date: "4TH MARCH",
    time: "1.40PM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG04",
    home: "MOORE WRIGHT GROUP",
    away: "OTEK BASKETBALL",
    conference: "WESTERN",
    day: "SAT",
    date: "4TH MARCH",
    time: "3.30PM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG05",
    home: "TEAM EXPERIENCE",
    away: "SWAT NATION",
    conference: "WESTERN",
    day: "SAT",
    date: "4TH MARCH",
    time: "5.30PM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG06",
    home: "PRIDE LANDERS",
    away: "TWENDE SPORTS",
    conference: "EASTERN",
    day: "SUN",
    date: "5TH MARCH",
    time: "10.00AM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG07",
    home: "RUIRU BAPTIST",
    away: "SEVEN ELEVEN",
    conference: "EASTERN",
    day: "SUN",
    date: "5TH MARCH",
    time: "11.50AM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG08",
    home: "CLIQUE MAMBAS",
    away: "BROWNING",
    conference: "EASTERN",
    day: "SUN",
    date: "5TH MARCH",
    time: "1.40PM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG09",
    home: "DEMENTERS",
    away: "KIBRA",
    conference: "EASTERN",
    day: "SUN",
    date: "5TH MARCH",
    time: "3.40PM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG10",
    home: "SUNRISE",
    away: "FAM KENYA",
    conference: "EASTERN",
    day: "SUN",
    date: "5TH MARCH",
    time: "5.30PM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG11",
    home: "NASRA EAGLES",
    away: "RUIRU BAPTIST",
    conference: "EASTERN",
    day: "SAT",
    date: "11TH MARCH",
    time: "9.30AM",
    court: "DIWOPA",
    location: "KAYOLE",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG12",
    home: "BURU CRUSADERS",
    away: "PRIDE LANDERS",
    conference: "EASTERN",
    day: "SAT",
    date: "11TH MARCH",
    time: "11.00AM",
    court: "DIWOPA",
    location: "KAYOLE",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG13",
    home: "DEMENTERS",
    away: "FAM KENYA",
    conference: "EASTERN",
    day: "SAT",
    date: "11TH MARCH",
    time: "12.30PM",
    court: "DIWOPA",
    location: "KAYOLE",
    results: "",
    notes: "",
  },
  {
    gameNo: "GWLG01",
    home: "TWENDE SPORTS",
    away: "SWAT NATION",
    conference: "LADIES",
    day: "SAT",
    date: "11TH MARCH",
    time: "2.00PM",
    court: "DIWOPA",
    location: "KAYOLE",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG14",
    home: "KIBRA",
    away: "SUNRISE",
    conference: "EASTERN",
    day: "SAT",
    date: "11TH MARCH",
    time: "3.30PM",
    court: "DIWOPA",
    location: "KAYOLE",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG15",
    home: "CLIQUE MAMBAS",
    away: "TWENDE SPORTS",
    conference: "EASTERN",
    day: "SAT",
    date: "11TH MARCH",
    time: "5.00PM",
    court: "DIWOPA",
    location: "KAYOLE",
    results: "",
    notes: "",
  },
  {
    gameNo: "GSLG16",
    home: "JERICHO NETS",
    away: "TEAM EXPERIENCE",
    conference: "WESTERN",
    day: "SAT",
    date: "11TH MARCH",
    time: "10.00AM",
    court: "KFC COURT",
    location: "KOMAROCK",
    results: "",
    notes: "",
  },
  {
    id: "GSLG17",
    homeTeam: "SWAT NATION",
    awayTeam: "MOORE WRIGHT GROUP",
    region: "WESTERN",
    date: "SAT, 11TH MARCH",
    time: "11.30AM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    id: "GSLG18",
    homeTeam: "BANTU SPORTS",
    awayTeam: "HURUMA DRAGON",
    region: "WESTERN",
    date: "SAT, 11TH MARCH",
    time: "1.00PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    id: "GWLG02",
    homeTeam: "MOORE WRIGHT GROUP",
    awayTeam: "STINGERS LADIES",
    region: "WESTERN",
    date: "SAT, 11TH MARCH",
    time: "2.30PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    id: "GSLG19",
    homeTeam: "JUNUBIN",
    awayTeam: "JERICHO VIPERS",
    region: "WESTERN",
    date: "SAT, 11TH MARCH",
    time: "4.00PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    id: "GSLG20",
    homeTeam: "FEBA ACADEMY",
    awayTeam: "SAVIO",
    region: "WESTERN",
    date: "SAT, 11TH MARCH",
    time: "5.30PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    gameCode: "GSLG21",
    team1: "DEMENTERS",
    team2: "NASRA",
    region: "EASTERN",
    day: "SUN",
    date: "12TH MARCH",
    time: "10.00AM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    gameCode: "GSLG22",
    team1: "FAM KENYA",
    team2: "KIBRA",
    region: "EASTERN",
    day: "SUN",
    date: "12TH MARCH",
    time: "11.30AM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    gameCode: "GWLG03",
    team1: "BOMBEEZ",
    team2: "SCARLETS LADIES",
    region: "SUN",
    day: "SUN",
    date: "12TH MARCH",
    time: "1.00PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    gameCode: "GSLG23",
    team1: "CLIQUE MAMBAS",
    team2: "BURU CRUSADERS",
    region: "EASTERN",
    day: "SUN",
    date: "12TH MARCH",
    time: "2.30PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    gameCode: "GSLG24",
    team1: "RUIRU BAPTIST",
    team2: "TWENDE SPORTS",
    region: "EASTERN",
    day: "SUN",
    date: "12TH MARCH",
    time: "4.00PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    gameCode: "GSLG25",
    team1: "SUNRISE",
    team2: "SEVEN ELEVEN",
    region: "EASTERN",
    day: "SUN",
    date: "12TH MARCH",
    time: "5.30PM",
    venue: "KFC COURT",
    location: "KOMAROCK",
  },
  {
    "GAME NO.": "GSLG26",
    HOME: "MOORE WRIGHT GROUP",
    AWAY: "JERCHO NETS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "9.30AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG27",
    HOME: "HURUMA DRAGON",
    AWAY: "FEBA ACADEMY",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "11.00AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG04",
    HOME: "SCARLETS",
    AWAY: "ACTIVE NATION LADIES",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "12.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG28",
    HOME: "TEAM EXPERIENCE",
    AWAY: "JERICHO VIPERS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "2.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG29",
    HOME: "OTEK BASKETBALL",
    AWAY: "SWAT NATION",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "3.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG30",
    HOME: "JUNUBIN",
    AWAY: "BANTU SPORTS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "5.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG31",
    HOME: "NASRA",
    AWAY: "SUNRISE",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG32",
    HOME: "PRIDE LANDERS",
    AWAY: "CLIQUE MAMBAS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG05",
    HOME: "MONEY TEAM",
    AWAY: "SCARLETS LADIES",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG33",
    HOME: "BURU CRUSADERS",
    AWAY: "RUIRU BAPTIST",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG34",
    HOME: "SEVEN ELEVEN",
    AWAY: "FAM KENYA",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG35",
    HOME: "TWENDE SPORTS",
    AWAY: "DEMENTERS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "18TH MARCH",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG36",
    HOME: "JERICHO NETS",
    AWAY: "OTEK BASKETBALL",
    CONFERENCE: "WESTERN",
    DAY: "SUN",
    DATE: "19TH MARCH",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG37",
    HOME: "SAVIO",
    AWAY: "HURUMA DRAGONS",
    CONFERENCE: "WESTERN",
    DAY: "SUN",
    DATE: "19TH MARCH",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG06",
    HOME: "STINGERS",
    AWAY: "BOMBEEZ",
    CONFERENCE: "LADIES",
    DAY: "SUN",
    DATE: "19TH MARCH",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG07",
    HOME: "SWAT",
    AWAY: "MOORE WRIGHT GROUP",
    CONFERENCE: "LADIES",
    DAY: "SUN",
    DATE: "19TH MARCH",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG38",
    HOME: "JERICHO VIPERS",
    AWAY: "MOORE WRIGHT GROUP",
    CONFERENCE: "WESTERN",
    DAY: "SUN",
    DATE: "19TH MARCH",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG39",
    HOME: "BANTU SPORTS",
    AWAY: "TEAM EXPERIENCE",
    CONFERENCE: "WESTERN",
    DAY: "SUN",
    DATE: "19TH MARCH",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG40",
    HOME: "FAM KENYA",
    AWAY: "NASRA EAGLES",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "9.30AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG41",
    HOME: "DEMENTERS",
    AWAY: "BURU CRUSADERS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "11.00AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG07",
    HOME: "ACTIVE NATION",
    AWAY: "TWENDE SPORTS",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "12.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG42",
    HOME: "SUNRISE",
    AWAY: "TWENDE SPORTS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "2.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG43",
    HOME: "SEVEN ELEVEN",
    AWAY: "KIBRA",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "3.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG44",
    HOME: "RUIRU BAPTIST",
    AWAY: "PRIDE LANDERS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "5.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG45",
    HOME: "MOORE WRIGHT GROUP",
    AWAY: "BANTU SPORTS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG08",
    HOME: "SCARLETS",
    AWAY: "STINGERS LADIES",
    CONFERENCE: "",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG46",
    HOME: "SWAT NATION",
    AWAY: "JERICHO NETS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG47",
    HOME: "TEAM EXPERIENCE",
    AWAY: "FEBA ACADEMY",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG48",
    HOME: "OTEK BASKETBALL",
    AWAY: "JERICHO VIPERS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG49",
    HOME: "JUNUBIN",
    AWAY: "SAVIO",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "25TH MARCH",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG50",
    HOME: "KIBRA",
    AWAY: "NASRA EAGLES",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "26TH MARCH",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG51",
    HOME: "PRIDE LANDERS",
    AWAY: "DEMENTERS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "26TH MARCH",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG52",
    HOME: "BURU CRUSADERS",
    AWAY: "SUNRISE",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "26TH MARCH",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG09",
    HOME: "BOMBEEZ",
    AWAY: "SWAT NATION",
    CONFERENCE: "LADIES",
    DAY: "SUN",
    DATE: "26TH MARCH",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG54",
    HOME: "CLIQUE MAMBAS",
    AWAY: "RUIRU BAPTIST",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "26TH MARCH",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG55",
    HOME: "TWENDE SPORTS",
    AWAY: "FAM KENYA",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "26TH MARCH",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG58",
    HOME: "HURUMA DRAGONS",
    AWAY: "JUNUBIN",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "11.00AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG59",
    HOME: "JERICHO VIPERS",
    AWAY: "SWAT NATION",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "12.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG10",
    HOME: "TWENDE SPORTS",
    AWAY: "MOORE WRIGHT GROUP",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "2.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG61",
    HOME: "BANTU SPORTS",
    AWAY: "OTEK BASKETBALL",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "3.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG62",
    HOME: "SAVIO",
    AWAY: "TEAM EXPERIENCE",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "5.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG63",
    HOME: "DEMENTERS",
    AWAY: "CLIQUE MAMBERS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG64",
    HOME: "SEVEN ELEVEN",
    AWAY: "NASRA EAGLES",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG65",
    HOME: "SUNRISE",
    AWAY: "PRIDE LANDERS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG11",
    HOME: "SWAT NATION",
    AWAY: "SCARLETS",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG12",
    HOME: "MONEY TEAM",
    AWAY: "TWENDE SPORTS",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG68",
    HOME: "FAM KENYA",
    AWAY: "BURU CRUSADERS",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "1ST APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG75",
    HOME: "RUIRU BAPTIST",
    AWAY: "DEMENTORS",
    CONFERENCE: "EASTERN",
    DAY: "FRI",
    DATE: "7TH APRIL",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG76",
    HOME: "PRIDE LANDERS",
    AWAY: "FAM KENYA",
    CONFERENCE: "EASTERN",
    DAY: "FRI",
    DATE: "7TH APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG77",
    HOME: "CLIQUE MAMBAS",
    AWAY: "SUNRISE",
    CONFERENCE: "EASTERN",
    DAY: "FRI",
    DATE: "7TH APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG15",
    HOME: "ACTIVE NATION",
    AWAY: "MONEY TEAM",
    CONFERENCE: "LADIES",
    DAY: "FRI",
    DATE: "7TH APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG79",
    HOME: "BURU CRUSADERS",
    AWAY: "KIBRA",
    CONFERENCE: "EASTERN",
    DAY: "FRI",
    DATE: "7TH APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG80",
    HOME: "TWENDE SPORTS",
    AWAY: "SEVEN ELEVEN",
    CONFERENCE: "EASTERN",
    DAY: "FRI",
    DATE: "7TH APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG16",
    HOME: "MOORE WRIGHT GROUP",
    AWAY: "ACTIVE NATION",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "12.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },

  {
    "GAME NO.": "GWLG17",
    HOME: "STINGERS",
    AWAY: "BOMBEEZ",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "2.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },

  {
    "GAME NO.": "GWLG18",
    HOME: "TWENDE SPORTS",
    AWAY: "SCARLETS",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "3.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },

  {
    "GAME NO.": "GWLG19",
    HOME: "SWAT NATION",
    AWAY: "MONEY TEAM",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "5.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG81",
    HOME: "HURUMA DRAGON",
    AWAY: "MOORE WRIGHT GROUP",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG82",
    HOME: "BANTU SPORTS",
    AWAY: "JERICHO NETS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG83",
    HOME: "JUNUBIN",
    AWAY: "TEAM EXPERIENCE",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG84",
    HOME: "FEBA ACADEMY",
    AWAY: "SWAT NATION",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG85",
    HOME: "SAVIO",
    AWAY: "OTEK BASKETBALL",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "8TH APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG86",
    HOME: "KIBRA",
    AWAY: "PRIDE LANDERS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "9TH APRIL",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG87",
    HOME: "NASRA  EAGLES",
    AWAY: "TWENDE SPORTS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "9TH APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG88",
    HOME: "SUNRISE",
    AWAY: "RUIRU BAPTIST",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "9TH APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG20",
    HOME: "TWENDE SPORTS",
    AWAY: "BOMBEEZ",
    CONFERENCE: "LADIES",
    DAY: "SUN",
    DATE: "9TH APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG90",
    HOME: "FAM KENYA",
    AWAY: "CLIQUE MAMBAS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "9TH APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG91",
    HOME: "SEVEN ELEVEN",
    AWAY: "BURU CRUSADERS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "9TH APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG92",
    HOME: "JERICHO NETS",
    AWAY: "FEBA ACADEMY",
    CONFERENCE: "WESTERN",
    DAY: "MON",
    DATE: "10TH APRIL",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG93",
    HOME: "MOORE WRIGHT GROUP",
    AWAY: "JUNUBIN",
    CONFERENCE: "WESTERN",
    DAY: "MON",
    DATE: "10TH APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG94",
    HOME: "JERICHO VIPERS",
    AWAY: "BANTU SPORTS",
    CONFERENCE: "WESTERN",
    DAY: "MON",
    DATE: "10TH APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG21",
    HOME: "STINGERS",
    AWAY: "SWAT NATION",
    CONFERENCE: "LADIES",
    DAY: "MON",
    DATE: "10TH APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG96",
    HOME: "OTEK BASKTBALL",
    AWAY: "HURUMA DRAGON",
    CONFERENCE: "WESTERN",
    DAY: "MON",
    DATE: "10TH APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG97",
    HOME: "SWAT",
    AWAY: "SAVIO",
    CONFERENCE: "WESTERN",
    DAY: "MON",
    DATE: "10TH APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG98",
    HOME: "DEMENTER",
    AWAY: "SUNRISE",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "9.30AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG99",
    HOME: "PRIDE LANDERS",
    AWAY: "SEVEN ELEVEN",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "11.00AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG100",
    HOME: "BURU CRUSADERS",
    AWAY: "NASRA EAGLES",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "12.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG23",
    HOME: "ACTIVE NATION",
    AWAY: "SWAT NATION LADIES",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "2.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG102",
    HOME: "RUIRU BAPTIST",
    AWAY: "FAM KENYA",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "3.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG103",
    HOME: "CLIQUE MAMBAS",
    AWAY: "KIBRA",
    CONFERENCE: "EASTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "5.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG104",
    HOME: "FEBA ACADEMY",
    AWAY: "JERICHO VIPERS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG105",
    HOME: "SAVIO",
    AWAY: "JERICHO NETS",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG24",
    HOME: "MONEY TEAM",
    AWAY: "MOORE WRIGHT GROUP",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG107",
    HOME: "HURUMA DRAGON",
    AWAY: "SWAT NATION",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG108",
    HOME: "JUNUBIN",
    AWAY: "OTEK BASKETBALL",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG109",
    HOME: "TEAM EXPERIENCE",
    AWAY: "MOORE WRIGHT GROUP",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "15TH APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG110",
    HOME: "SEVEN ELEVEN",
    AWAY: "DEMENTERS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "16TH APRIL",
    TIME: "10.00AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG111",
    HOME: "NASRA EAGLES",
    AWAY: "PRIDE LANDERS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "16TH APRIL",
    TIME: "11.30AM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG25",
    HOME: "BOMBEEZ",
    AWAY: "MONEY TEAM",
    CONFERENCE: "LADIES",
    DAY: "SUN",
    DATE: "16TH APRIL",
    TIME: "1.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG113",
    HOME: "SEVEN ELEVEN",
    AWAY: "CLIQUE MAMBAS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "16TH APRIL",
    TIME: "2.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG114",
    HOME: "TWENDE SPORTS",
    AWAY: "BURU CRUSADERS",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "16TH APRIL",
    TIME: "4.00PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG115",
    HOME: "KIBRA",
    AWAY: "RUIRU BAPTIST",
    CONFERENCE: "EASTERN",
    DAY: "SUN",
    DATE: "16TH APRIL",
    TIME: "5.30PM",
    COURT: "KFC COURT",
    LOCATION: "KOMAROCK",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG116",
    HOME: "JERICHO VIPERS",
    AWAY: "SAVIO",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "22ND APRIL",
    TIME: "9.30AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG117",
    HOME: "JERICHO NETS",
    AWAY: "HURUMA DRAGON",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "22ND APRIL",
    TIME: "11.00AM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG26",
    HOME: "ACTIVE NATION",
    AWAY: "BOMBEEZ",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "22ND APRIL",
    TIME: "12.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GWLG27",
    HOME: "MONEY TEAM",
    AWAY: "STINGERS",
    CONFERENCE: "LADIES",
    DAY: "SAT",
    DATE: "22ND APRIL",
    TIME: "2.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG120",
    HOME: "OTEK BASKETBALL",
    AWAY: "TEAM EXPERIENCE",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "22ND APRIL",
    TIME: "3.30PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
  {
    "GAME NO.": "GSLG121",
    HOME: "BANTU SPORTS",
    AWAY: "FEBA ACADEMY",
    CONFERENCE: "WESTERN",
    DAY: "SAT",
    DATE: "22ND APRIL",
    TIME: "5.00PM",
    COURT: "DIWOPA",
    LOCATION: "KAYOLE",
    RESULTS: "",
    NOTES: "",
  },
];
